# Generated by Django 5.2.4 on 2025-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_model', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
